apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdgarts
  labels:
    app: sdgarts
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdgarts
  template:
    metadata:
      labels:
        app: sdgarts
    spec:
      containers:
        - name: sdgarts
          image: clickocean.io/automation/image
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 50m
              memory: 200Mi
      imagePullSecrets:
        - name: regcred
