apiVersion: v1
kind: Service
metadata:
  name: sdgarts
  namespace: web
spec:
  type: ClusterIP
  selector:
    app: sdgarts
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
