apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdgarts-ingress
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(.*)/$ /$1 permanent;
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
    nginx.ingress.kubernetes.io/custom-http-errors: '404=/404'
spec:
  ingressClassName: nginx
  rules:
    - host: 'sdgarts.foundation'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sdgarts
                port:
                  number: 80
